name       : subtitlecomposer
version    : 0.7.1
release    : 9
source     :
    - https://invent.kde.org/multimedia/subtitlecomposer/-/archive/v0.7.1/subtitlecomposer-v0.7.1.tar.bz2 : d7834346525813c3d5762c45fdbea2ef49c2db7d07af86b779b376e04c982e88
license    : GPL-2.0-or-later
component  : multimedia.video
optimize   : lto
summary    : Video subtitle editor that supports basic and advanced editing operations
description: |
    Subtitle Composer is an open source text-based subtitle editor that supports basic and advanced editing operations.
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(libavcodec)
    - pkgconfig(openal)
    - extra-cmake-modules
    - kross-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
