name       : subtitlecomposer
version    : 0.7.0
release    : 4
source     :
    - https://invent.kde.org/multimedia/subtitlecomposer/-/archive/v0.7.0/subtitlecomposer-v0.7.0.tar.gz : d2f0e2f7ababa210a13d79d808eed65838e53784a590dac87566205fea2689ea
license    : GPL-2.0-or-later
component  : multimedia.video
optimize   : lto
summary    : Video subtitle editor that supports basic and advanced editing operations
description: |
    Subtitle Composer is an open source text-based subtitle editor that supports basic and advanced editing operations.
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(icu-i18n)
    - pkgconfig(libavcodec)
    - extra-cmake-modules
    - kross-devel
    - kwindowsystem-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove mplayer plugin, because we don't provide mplayer in the repository
    rm -v $installdir/usr/lib64/subtitlecomposer/mplayer.so

    # Remove icons for other features which we don't build
    rm -v $installdir/usr/share/subtitlecomposer/icons/hicolor/48x48/apps/{mplayer,xine}.png
    rm -rfv $installdir/usr/share/subtitlecomposer/icons/hicolor/64x64/
check      : |
    %ninja_check
